#language: java
#
#jdk:
#  - oraclejdk8
#  - openjdk7
#
#before_install:
#  - cd java

language: java
jdk: oraclejdk8
sudo: false
script: mvn clean verify



cache:
    directories:
        - $HOME/.m2

#before_install:
# - cd java
#before_install:
#  - cd java
#  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
